/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
    @Test void BlackAndWhite() {
        String str = "/home/renad/Desktop/LTUCTraining/Advance/bitmap-transformer/app/src/main/resources";
        String path = "input.bmp";
        BitMap classUnderTest = new BitMap(path);
        assertEquals("The Color is Changed",classUnderTest.BlackAndWhite("/home/renad/Desktop/LTUCTraining/Advance/bitmap-transformer/app/src/main/resources"));

    }

    @Test void invert() {
        String path = "input.bmp";
        BitMap classUnderTest = new BitMap(path);
        assertEquals("The new image is created Successfully :)",classUnderTest.invert("/home/renad/Desktop/LTUCTraining/Advance/bitmap-transformer/app/src/main/resources"));

    }

    @Test void mirrorImage() {
        String path = "input.bmp";
        BitMap classUnderTest = new BitMap(path);
        assertEquals("The new image is created Successfully :)",classUnderTest.invert("/home/renad/Desktop/LTUCTraining/Advance/bitmap-transformer/app/src/main/resources"));

    }
}


